### ISSUE TITLE
[DÚVIDA] - Layout Figma

### ISSUE THREAD

**Issue by HMontarroyos** [codante-io/rinha-frontend#15]
O Layout da Rinha de Front-end precisa seguir exatamente o que está no figma ou é so para ter uma base ? Por exemplo eu posso estilizar das cores ou fontes que eu quiser etc ...

**Comment by itsfpbtw** [comment]
Também gostaria de saber.

**Comment by viniciussantos45** [comment]
Estou em dúvida tbm, como é rinha de front end e não posso pintar os botão? Hehehe

**Comment by icaroharry** [comment]
Salve galera! Perdão pela demora pra responder.

A fidelidade ao layout **não é** um critério de avaliação. A gente quis simplificar ao máximo o layout pra poder focar no desafio principal de trabalhar com JSONs pesados.

Então não tem problema alterar o layout, mas isso não vai trazer vantagens na hora da avaliação.

Resumindo: não precisa seguir o figma, mas fazer um layout bonito não vai te trazer mais pontos 😄

**Comment by filipeleonelbatista** [comment]
> Salve galera! Perdão pela demora pra responder.
> 
> A fidelidade ao layout **não é** um critério de avaliação. A gente quis simplificar ao máximo o layout pra poder focar no desafio principal de trabalhar com JSONs pesados.
> 
> Então não tem problema alterar o layout, mas isso não vai trazer vantagens na hora da avaliação.
> 
> Resumindo: não precisa seguir o figma, mas fazer um layout bonito não vai te trazer mais pontos 😄

Poxa se é rinha de frontend deveria ser respeitado e contar como critérios kkkkk. Enfim. Minha dúvida seria, o JSON vem aberto por padrão? Ou teria a opção de colapsar os objetos/arrays?
Essa marca na lateral que  está em destaque?

**Comment by icaroharry** [comment]
Só pra dar um pouco de contexto: a ideia inicial era dar pontos pra quem seguisse o layout, mas quando aprofundamos nas implementações, vimos que algumas implementações necessitariam de um layout diferente. Por ex: se alguém quiser fazer uma paginação com scroll infinito e outra pessoa com páginas. Se a gente obriga todo mundo a seguir um layout a risca, a gente estaria "engessando" um pouco as soluções possíveis.

Concordo que é estranho na rinha de front-end isso não ser um critério, mas escolhas difíceis precisam ser feitas kkkkk. Optamos por priorizar outros aspectos.

Por fim, respondendo sua pergunta: **pode sim**, colapsar/expandir os objetos/arrays. Esse foi um dos casos que pensamos que "quebraria" o layout mas é uma solução válida,

**Comment by elonager** [comment]
Gostaria de saber se é necessário ter várias páginas como a disposição do figma sugere (index.html, json Tree Viewer, e error). Ou se posso resolver tudo em uma única página, que será alterada conforme a interação.
Também notei que na tela de visualização do Json não tem um botão de voltar, ele é necessário? Contará pontos de desempate caso tenha?
