### ISSUE TITLE
[DÚVIDA] - Precisa fazer expand/collapse na tree?

### ISSUE THREAD

**Issue by andrody** [codante-io/rinha-frontend#17]
O objetivo é apenas mostrar o json formatado ou precisa fazer o collapse/expand dos valores de array e objetos?

**Comment by icaroharry** [comment]
Salve @andrody!

A estratégia de renderização da tree é livre. Você pode fazer o collapse/expand se fizer sentido pra sua implementação, mas não é obrigatório.

Abraço!
