### ISSUE TITLE
[DÚVIDA] - Extratégias de carregamento

### ISSUE THREAD

**Issue by filipeleonelbatista** [codante-io/rinha-frontend#18]
De certo modo consegui carregar quase todos, exceto o `giant.json` 😅. Estou em dúvidas sobre as estratégias de carregamento. Hoje eu inicio o objeto fechado, ou seja com todos os filhos fechados e vou abrindo conforme necessário. Mas atualmente quando eu envio o json no campo eu alimento o estado com a totalidade do json, até aí ok, aparentemente, mas quando expande os dados aí ele trava. Enfim. O que fazer?

Estou usando React, TS com Vite e tailwind.

Ja fiz o deploy nester link

https://rinha-frontend-filipeleonelbatista.vercel.app/

**Comment by ghost** [comment]
Existem várias formas de resolver o seu problema, mas a primeira que precisamos entender é: por que o seu (e outros projetos) travam completamente quando o `giant.json` é carregado? O motivo principal é: tentar alocar todo o arquivo em memória, na mesma thread que a interface está rodando.

É de fato possível executar código no browser em outras threads por meio de [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), embora isso não vá solucionar todo o problema se você não tiver uma boa estratégia de renderização, mas já ajuda um pouco.
Se você enviar o arquivo para um worker, a interface não irá travar enquanto o parse do JSON é feito (assumindo que você vai usar `JSON.parse` do próprio JS), mas vai travar se você devolver todo o objeto de volta pra thread principal, pelo simples fato do worker ter de serializar os dados e a main thread ter de de-serializar de volta.

Sempre tente trabalhar com pedaços ao invés de alocar um arquivo ou um objeto de 200MB :)
