### ISSUE TITLE
[DÚVIDA] - Collapse dos subníveis

### ISSUE THREAD

**Issue by reinaldorauch** [codante-io/rinha-frontend#19]
Na descrição do projeto não fica claro se é necessário ou não adicionar collapse pros subíveis de objetos/arrays. Será necessário ou só precisa mostrar tudo abertão mesmo?

**Comment by icaroharry** [comment]
Fala @reinaldorauch :D

Não é obrigatório, mas é permitido. Isso vai da sua estratégia.

Se você optar por renderizar tudo aberto por algum motivo de performance, é válido. Por outro lado se você quiser priorizar acessibilidade e fazer o collapse/expand, é válido também.

_(citei exemplos aleatórios de motivos pra tomada de decisão, o ponto é: você decide de acordo com a sua estratégia)_

Faz sentido?
