### ISSUE TITLE
[AJUDA] - Corrigir submissão

### ISSUE THREAD

**Issue by victortbezerra** [codante-io/rinha-frontend#24]
Gostaria de alterar o link de submissão, pus o errado, era pra ser esse: https://victortbezerra.github.io/rinha-frontend/

**Comment by icaroharry** [comment]
Fala @victortbezerra! Beleza?

Corrigi o link aqui. Pode confirmar se deu certo? Aí eu corrijo a screenshot. 😄 

Abraço!

**Comment by icaroharry** [comment]
Pronto. Corrigido!

**Comment by victortbezerra** [comment]
Corrigido, muito obrigado ;)

**Comment by victortbezerra** [comment]
Poderia atualizar o screenshot? Dei uma ajeitada no CSS
