### ISSUE TITLE
[DÚVIDA] Histórico de desenvolvimento

### ISSUE THREAD

**Issue by Kecbm** [codante-io/rinha-frontend#26]
Participar da rinha é um desafio enorme para mim pois todos os temas abordados são novos, estarei aprendendo em tempo de desenvolvimento. Sendo assim queria manter na aplicação final todas as soluções que irei desenvolver até o dia 31, eu posso fazer isso? A minha ideia era manter a versão final para ser avaliada na página home da aplicação e as demais em outras páginas com botões navegáveis para cada uma delas. Porém fico com dúvida sobre manter todo esse código, pois acho que afetaria na hora de analise da entrega final de alguma forma, como por exemplo na acessibilidade. Ou é melhor fazer essa documentação de etapas de uma outra forma, como por exemplo utilizando branchs exclusivas para cada uma delas e fazendo o deploy apenas da branch com a versão final do código?

**Comment by icaroharry** [comment]
Oi @Kecbm! 

Caso a sua versão final consiga carregar o maior JSON (giant.json), minha sugestão pra você é submetê-la de forma "pura" sem links pra outros códigos. Porque isso pode afetar na avaliação de performance que vamos fazer. 

Caso a sua versão não carregue o maior JSON de todos, nós não vamos fazer os testes de performance nela (já que esse é o primeiro critério de desempate), então não vai fazer diferença ter coisas a mais.

Uma outra ideia pra você é fazer vários deploys diferentes e colocar no README a documentação falando de cada um deles :)

**Comment by Kecbm** [comment]
Obrigada pelo esclarecimento @icaroharry, vou deixar apenas a versão final no repo e documentar as outras versões em outro lugar pra não atrapalhar a avaliação 😁

**Comment by Kecbm** [comment]
Obrigada pelo esclarecimento @icaroharry, vou deixar apenas a versão final no repo e documentar as outras versões em outro lugar pra não atrapalhar a avaliação 😁
