### ISSUE TITLE
[SUGESTÃO] Correção do arquivo invalid.json

### ISSUE THREAD

**Issue by Kecbm** [codante-io/rinha-frontend#27]
Codifiquei minha primeira solução para a rinha e estou testando quais arquivos ela é capaz de renderizar. Ao submeter o arquivo invalid.json para renderização apareceu esse erro:

![Erro - rinha](https://github.com/codante-io/rinha-frontend/assets/67391952/a1e95c67-9165-4a24-ae87-11c19bf5b5e7)

Fui verificar a estrutura do arquivo e faltava a chave de fechamento "}" no final do arquivo. Após adicionar essa chave no arquivo e salvar a alteração a renderização rodou corretamente. Alô @icaroharry e @felippe-regazio, estou pronta pra abrir esse PR e ter minha fotinha ali no repositório como contribuidora em. Uma chave abre muitas portas 😁

**Comment by ghost** [comment]
Como o nome do arquivo sugere, ele está com erro de propósito, para que você possa testar como seu projeto se comporta com arquivos incorretos.
De acordo com as regras:
`Correctness: Esse é o critério principal: A aplicação deve funcionar. Um JSON deve poder ser carregado e exibido conforme demonstrado no Layout (não necessariamente precisa ser o maior JSON, mas ao menos alguns deles). Além disso, aqui também vamos analisar como sua aplicação se comporta no caso de JSONs inválidos.`

**Comment by icaroharry** [comment]
Ei @Kecbm!

É isso mesmo que o @heliokroger falou. Você precisa verificar se o JSON é válido e mostrar um erro caso não seja.

**Comment by Kecbm** [comment]
Massa demais! Nesse caso o errado tá certo kkk. Obrigada pela explicação @heliokroger e @icaroharry 😁
