### ISSUE TITLE
[SUGESTÃO] Adicionar link do site onde você se inscreve no projeto

### ISSUE THREAD

**Issue by bosi-programming** [codante-io/rinha-frontend#29]
Li todo o READMe do projeto e não achei por onde me inscrever na rinha (https://codante.io/mini-projetos/rinha-frontend). Cheguei primeiro por aqui e tive que procurar no Google onde me inscrever. Sei que não é um grande esforço, mas uns cliques a menos sempre deixa todo mundo mais feliz.

**Comment by icaroharry** [comment]
Ótima sugestão @bosi-programming! Vou colocar aqui

**Comment by icaroharry** [comment]
Done
