### ISSUE TITLE
[AJUDA] Preciso trocar a URL da minha submissão

### ISSUE THREAD

**Issue by ghost** [codante-io/rinha-frontend#33]
Estava trabalhando num repositório privado antes de fazer o fork, que estava sendo feito deploy para a URL `json-tree-viewer.pages.dev`, mas agora que eu fiz o fork do repositório da rinha e troquei o nome do projeto no CloudFlare, o domínio passou a ser `rinha-frontend.pages.dev`. Não consegui encontrar nenhuma opção para trocar a URL da submissão no side da Codante.

**Comment by icaroharry** [comment]
Fala @heliokroger! Desculpa pela demora.

Vou corrigir aqui pra você. A gente ainda não tem a feature de editar a submissão

**Comment by icaroharry** [comment]
Done!
