### ISSUE TITLE
[DÚVIDA] Formato de exibição dos dados

### ISSUE THREAD

**Issue by mfornaciari** [codante-io/rinha-frontend#36]
No [exemplo do Figma](https://www.figma.com/file/Y079MhhStaGiaqAA8NaZ5E/Rinha-de-Front-end-(Community)?type=design&node-id=207-2&mode=dev), que usa o arquivo `alltypes.json`, é possível ver que:

- Os valores de `weight` são inteiros (67 e 77);
- Os valores do array `children` incluem sobrenomes ("Suri Cruise" e "Indio Falconer Downey", por exemplo).

Contudo, no [alltypes.json disponível no Drive](https://drive.google.com/drive/folders/1oO0AoBQukdF3_DxRYn1di7O4Iiqom1wJ), os valores de `weight` são floats (67.5 e 77.1), e os valores do array `children` não incluem sobrenomes ("Suri" e "Indio Falconer", por exemplo).

É esperado que tratemos esses valores para que eles sejam exibidos como no exemplo do Figma?

**Comment by Kecbm** [comment]
Olá @mfornaciari, tudo bem? O @icaroharry comentou nessa issue: https://github.com/codante-io/rinha-frontend/issues/15 que não é obrigatório seguir o exemplo do Figma, porque podem ter diversas soluções que se enquadram em layouts diferentes 😁
