### ISSUE TITLE
[AJUDA] Correção de projeto finalizado

### ISSUE THREAD

**Issue by guaracy** [codante-io/rinha-frontend#37]
Fiz uma correção no projeto mas havia marquei como finalizado.

A versão de https://guaracy.github.io/rinha-frontend/ está corrigida. 

Se foi feito download dos .arquivos (html,. css, .js) estarão incorretos. Se for direto pelo gh-pages está ok.

Obrigado.

**Comment by JoaoGuiLeao** [comment]
@guaracy Feche seu issues caso seu problema foi resolvido, e bom para limpar seu propio github
