### ISSUE TITLE
Definir premiação

### ISSUE THREAD

**Issue by icaroharry** [codante-io/rinha-frontend#6]
Vale presente Kabum

https://www.kabum.com.br/servicos-digitais/giftcard?page_number=1&page_size=20&facet_filters=eyJrYWJ1bV9wcm9kdWN0IjpbInRydWUiXSwibWFudWZhY3R1cmVyIjpbIkthQnVNISJdfQ==&sort=most_searched

1 - 200
2 - 150
3 - 100
4 - 50
5 - 50

**Comment by robertotcestari** [comment]
e se também déssemos uma caneca do codante? @icaroharry
