### ISSUE TITLE
Adicionar formulário de submissão do projeto e link pro GitHub

### ISSUE THREAD

**Issue by icaroharry** [codante-io/rinha-frontend#9]
Adicionar no formulário de submissão:
 - Link do twitter
 - Maior arquivo json que conseguiu carregar

**Comment by robertotcestari** [comment]
Criei apenas a parte do formulário. 
Não gostei muito pq nosso código ficou um pouco acoplado à rinha. Mas acho que talvez seja a solução mais simples/rápida para agora. 

Basicamente se o slug do miniprojeto é "rinha-frontend", ele mostra os campos adicionais. Além disso, criamos um field 'metadata' na tabela `challenge_user` e agora é possível passar metadata da submissão do usuário (o que pode ser utiilizado futuramente).
Estou apenas aceitando 2 campos no metadata (por questões de segurança), `twitter_username` e `rinha_largest_file`

Pode ver @icaroharry ?
